
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yasir
 */
public class otomasyon extends javax.swing.JFrame {

    /**
     * Creates new form otomasyon
     */
    public otomasyon() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        jFrame1.setVisible(false);
        uygulamaGiris();
        ilk_renkAtama();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        button_frame1_approve = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        label_secilenKategori = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textfield_eklenecekUrunAd = new javax.swing.JTextField();
        textfield_eklenecekUrunFiyat = new javax.swing.JTextField();
        button_urunEkleFrame2 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        buton_hesapSil = new javax.swing.JButton();
        label_toplamHesap = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buton_icecekler = new javax.swing.JButton();
        button_tatlilar = new javax.swing.JButton();
        buton_kahveler = new javax.swing.JButton();
        buton_anaYemekler = new javax.swing.JButton();
        buton_aperatifler = new javax.swing.JButton();
        buton_tost = new javax.swing.JButton();
        button_urunEkle = new javax.swing.JButton();
        label_kategoriIsim = new javax.swing.JLabel();
        button_urunSil = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("İstenilen Masa Sayısı:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(146, 17));

        button_frame1_approve.setText("Onayla");
        button_frame1_approve.setPreferredSize(new java.awt.Dimension(146, 17));
        button_frame1_approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_frame1_approveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_frame1_approve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_frame1_approve, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        label_secilenKategori.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setText("Eklenecek Ürünün Adı: ");

        jLabel5.setText("Eklenecek Ürünün Fiyatı:");

        button_urunEkleFrame2.setText("Ürün Ekle");
        button_urunEkleFrame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_urunEkleFrame2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_secilenKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_urunEkleFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_eklenecekUrunFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_eklenecekUrunAd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_secilenKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_eklenecekUrunAd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_eklenecekUrunFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_urunEkleFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jMenuItem1.setText("Ürün Sil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1520, 820));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(520, 760));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MASALAR");
        jLabel1.setMaximumSize(new java.awt.Dimension(175, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(175, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(175, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün", "Adet", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        buton_hesapSil.setText("Hesap Sil");
        buton_hesapSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_hesapSilActionPerformed(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        buton_icecekler.setText("İçecekler");
        buton_icecekler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_iceceklerActionPerformed(evt);
            }
        });

        button_tatlilar.setText("Tatlılar");
        button_tatlilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tatlilarActionPerformed(evt);
            }
        });

        buton_kahveler.setText("Kahveler");
        buton_kahveler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_kahvelerActionPerformed(evt);
            }
        });

        buton_anaYemekler.setText("Ana Yemekler");
        buton_anaYemekler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_anaYemeklerActionPerformed(evt);
            }
        });

        buton_aperatifler.setText("Aperatifler");
        buton_aperatifler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_aperatiflerActionPerformed(evt);
            }
        });

        buton_tost.setText("Tostlar");
        buton_tost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_tostActionPerformed(evt);
            }
        });

        button_urunEkle.setText("Ürün Ekle");
        button_urunEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_urunEkleActionPerformed(evt);
            }
        });

        label_kategoriIsim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_kategoriIsim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        button_urunSil.setText("Ürün Sil");
        button_urunSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_urunSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_icecekler, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_tatlilar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_kahveler, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_anaYemekler, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_aperatifler, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_tost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button_urunSil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_urunEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_kategoriIsim, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(label_kategoriIsim, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buton_icecekler, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_tatlilar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buton_kahveler, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buton_anaYemekler, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buton_aperatifler, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buton_tost, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_urunEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(button_urunSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buton_hesapSil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_toplamHesap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(406, 406, 406)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buton_hesapSil, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(label_toplamHesap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void uygulamaGiris()
    {
        button_urunEkle.setVisible(false);
            Connection con;
            con = null;
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Bağlantı nesnesi
                String strdatabase = "jdbc:ucanaccess://otomasyonVT.accdb"; //veritabanının ismi
                con = DriverManager.getConnection(strdatabase); //Access-java bağlantısnı sağlayan jdbc sürücüsü ile bağlantı oluşturuluyor
            } 
            catch (Exception e) {
                System.out.println("Bağlantı Hatası 1");
            }
            try {
                Statement stmt;
                stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM masa_sayisi");
                rs.next();
                int iCount = rs.getInt("rowcount") ;
                rs.close();
                rs = stmt.executeQuery("SELECT * FROM masa_sayisi ");
                rs.next();
                try
                {
                    masaSayisi= rs.getInt("masa_sayisi") ;
                }
                catch(Exception e)
                {
                    System.out.println("getInt");
                }
                if((iCount<1 )||(masaSayisi==0))
                {
                    
                    try {
                        stmt.executeUpdate("delete from masa_sayisi");
                        jFrame1.setSize(new Dimension(400, 160));
                        jFrame1.setVisible(true);   
                        System.out.println("yeni: "+masaSayisi);
                    }
                    catch(Exception e)
                    {
                        System.out.println("3");
                    }
                }
                else
                {              
                    System.out.println("Var: "+masaSayisi);
                    button_olusturMasa();
                }
            }
            catch(Exception e)
            {
                System.out.println("2");
            }  
    }
    
    int masaSayisi=0;
    private void button_frame1_approveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_frame1_approveActionPerformed
        Connection con;
        con = null;
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Bağlantı nesnesi
            String strdatabase = "jdbc:ucanaccess://otomasyonVT.accdb"; //veritabanının ismi
            con = DriverManager.getConnection(strdatabase); //Access-java bağlantısnı sağlayan jdbc sürücüsü ile bağlantı oluşturuluyor
            Statement stmt = con.createStatement();
            String strSQL;
            masaSayisi=Integer.valueOf(jTextField1.getText());
            
            try {
                    stmt = con.createStatement();
                    strSQL ="insert into masa_sayisi(masa_sayisi) Values("+masaSayisi+")";
                    stmt.executeUpdate(strSQL);
            }
            catch(Exception e)
            {
                    System.out.println("1:  "+e);
            }
            
            for(int i=1;i<=masaSayisi;i++)
            {
                try {
                    stmt = con.createStatement();
                    strSQL ="create table masa"+i+"(Urun VARCHAR(20) ,Adet int,Fiyat DOUBLE)";
                    stmt.executeUpdate(strSQL);
                }
                catch(Exception e)
                {
                    System.out.println("2:  "+e);
                }  
            }
        }
        catch(Exception e)
        {
             System.out.println("3:  "+e); 
        }
        button_olusturMasa();
        jTextField1.setText(null);
        jFrame1.setVisible(false);      
    }//GEN-LAST:event_button_frame1_approveActionPerformed

    private void buton_hesapSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_hesapSilActionPerformed
        vt_masaBosalt();
        vt_hesapTabloyaYaz();
    }//GEN-LAST:event_buton_hesapSilActionPerformed

    private void button_urunEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_urunEkleActionPerformed
        if(secilen_kategori!=null)
        {
            jFrame2.setSize(new Dimension(400, 320));
            jFrame2.setVisible(true);
            label_secilenKategori.setText(kategoriIsim);
        }
    }//GEN-LAST:event_button_urunEkleActionPerformed

    private void button_urunEkleFrame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_urunEkleFrame2ActionPerformed
        eklenecek_urun=textfield_eklenecekUrunAd.getText();
        urun_fiyat=Double.valueOf(textfield_eklenecekUrunFiyat.getText());
        vt_urunEkle();
        textfield_eklenecekUrunAd.setText("");
        textfield_eklenecekUrunFiyat.setText("");
        jFrame1.setVisible(false);
    }//GEN-LAST:event_button_urunEkleFrame2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if (evt.getClickCount() == 2){
            int satir=jTable2.getSelectedRow();
            urun_aktar=(String) jTable2.getValueAt(satir, 0);
            fiyat_aktar= (double) jTable2.getValueAt(satir, 1);
            vt_urunAktar();
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void buton_iceceklerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_iceceklerActionPerformed
        secilen_kategori="icecekler";
        button_urunEkle.setVisible(true);
        kategoriIsim="İçecekler";
        vt_urunTabloyaYaz();
    }//GEN-LAST:event_buton_iceceklerActionPerformed

    private void buton_kahvelerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_kahvelerActionPerformed
        secilen_kategori="kahveler";
        button_urunEkle.setVisible(true);
        kategoriIsim="Kahveler";
        vt_urunTabloyaYaz();
    }//GEN-LAST:event_buton_kahvelerActionPerformed

    private void button_tatlilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tatlilarActionPerformed
        secilen_kategori="tatlilar";
        button_urunEkle.setVisible(true);
        kategoriIsim="Tatlılar";
        vt_urunTabloyaYaz();
    }//GEN-LAST:event_button_tatlilarActionPerformed

    private void buton_anaYemeklerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_anaYemeklerActionPerformed
        secilen_kategori="ana_yemekler";
        button_urunEkle.setVisible(true);
        kategoriIsim="Ana Yemekler";
        vt_urunTabloyaYaz();
    }//GEN-LAST:event_buton_anaYemeklerActionPerformed

    private void buton_aperatiflerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_aperatiflerActionPerformed
        secilen_kategori="aperatifler";
        button_urunEkle.setVisible(true);
        kategoriIsim="Aperatifler";
        vt_urunTabloyaYaz();
    }//GEN-LAST:event_buton_aperatiflerActionPerformed

    private void buton_tostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_tostActionPerformed
        secilen_kategori="tostlar";
        button_urunEkle.setVisible(true);
        kategoriIsim="Tostlar";
        vt_urunTabloyaYaz();
    }//GEN-LAST:event_buton_tostActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int satir=jTable1.getSelectedRow();
        urun_aktar=(String)jTable1.getValueAt(satir, 0);
        vt_masadanUrunSil();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void button_urunSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_urunSilActionPerformed
        int satir=jTable2.getSelectedRow();
        urun_sil=(String)jTable2.getValueAt(satir, 0);
        vt_urunSil();
    }//GEN-LAST:event_button_urunSilActionPerformed
    
    
    String kategoriIsim=null;
    String secilen_kategori=null;
    String eklenecek_urun=null;
    double urun_fiyat=0;
    String urun_aktar;
    double fiyat_aktar;
    ArrayList<JButton> butonlar=new ArrayList<JButton>();
    int secilen_masa=0;
    
    public void vt_urunSil()
    {
        if(secilen_kategori!=null)
        {
            Connection con;
            con = null;
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Bağlantı nesnesi
                String strdatabase = "jdbc:ucanaccess://otomasyonVT.accdb"; //veritabanının ismi
                con = DriverManager.getConnection(strdatabase); //Access-java bağlantısnı sağlayan jdbc sürücüsü ile bağlantı oluşturuluyor
            } 
            catch (Exception e) {
                System.out.println("Bağlantı Hatası 1");
            }
            try {
                Statement stmt;
                String strSQL;
                stmt = con.createStatement();
                try {
                    strSQL ="delete from "+secilen_kategori+" where Urun='"+urun_sil+"'";
                    stmt.executeUpdate(strSQL);    
                }
                catch(Exception e)
                {
                    System.out.println("4");
                }
            }
            catch(Exception e)
            {
                System.out.println("2");
            }  
        }
        vt_urunTabloyaYaz();
    }
    
    public void button_olusturMasa()
    {
        int sutun=4;
        int satir;
        if(masaSayisi/sutun==0) satir=masaSayisi/4;
        else satir=(masaSayisi/4)+1;
        if(satir==1) satir=satir+1;
        GridLayout experimentLayout = new GridLayout(sutun,satir,15,15);
        jPanel1.setLayout(experimentLayout);
        
        for(int i=1;i<=masaSayisi;i++)
        {
            JButton button=new JButton("masa"+i);
            button.setText("Masa "+String.valueOf(i));
            Font myFont = new Font("Tahoma", Font.PLAIN,14);
            
            button.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e) {
                    Object obj = e.getSource();
                    for(int i=0;i<butonlar.size();i++)
                    {
                        if(obj==butonlar.get(i))
                        {
                            secilen_masa=i+1;
                            vt_hesapTabloyaYaz();
                            jPanel1.revalidate();
                            jPanel1.repaint();
                            repaint();
                            break;
                        }
                    }
                }}
            );
            
            button.setFont(myFont);
            jPanel1.add(button);
            butonlar.add(button);
        }
        jPanel1.revalidate();
        jPanel1.repaint();
        repaint();
    }
    
    
    
    int kontrol_kategori=0;
    public void vt_hesapTabloyaYaz()
    {
        if(secilen_masa!=0)
        {
            jLabel3.setText("Masa "+secilen_masa);
        }
        else jLabel3.setText("");
        Connection con;
        con = null;
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Bağlantı nesnesi
            String strdatabase = "jdbc:ucanaccess://otomasyonVT.accdb"; //veritabanının ismi
            con = DriverManager.getConnection(strdatabase); //Access-java bağlantısnı sağlayan jdbc sürücüsü ile bağlantı oluşturuluyor
        }
        catch(Exception e)
        {        
            System.out.println("bağlantı hatası");     
        }
        String strSQL ="select * from masa"+secilen_masa;
        try {
            Statement stmt = con.createStatement();
            Object[][] obj;
            
            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM masa"+secilen_masa);
            rs.next();
            int iCount = rs.getInt("rowcount") ;
            rs.close() ;
            
            rs = stmt.executeQuery(strSQL);

            obj= new Object [iCount][3];
            if(iCount==0)
            {
                buton_hesapSil.setVisible(false);
                masa_renk(0);
            }
            else
            {
                buton_hesapSil.setVisible(true);
                masa_renk(1);
            }

            iCount = 0;
            double toplam_hesap=0;
            while ( rs.next() ) 
            {
                obj[iCount][0] = rs.getString("Urun");
                obj[iCount][1] = rs.getInt("Adet");
                obj[iCount][2] = rs.getDouble("Fiyat")+" TL";
                toplam_hesap=toplam_hesap+(rs.getInt("Adet")*rs.getDouble("Fiyat"));
                iCount = iCount+1;
            }
            if(toplam_hesap==0)
            {
                label_toplamHesap.setVisible(false);
            }
            else
            {
                label_toplamHesap.setVisible(true);
                label_toplamHesap.setText("HESAP: "+String.valueOf(toplam_hesap) +" TL");
            }
            DefaultTableModel model=new javax.swing.table.DefaultTableModel(obj,new String [] {"Ürün", "Adet", "Birim Fiyat"})
            {
                @Override
                public boolean isCellEditable(int row, int column) {
                return false;
                }
            };
            
            jTable1.setModel(model);
            jTable1.setUpdateSelectionOnSort(false);
            rs.close() ; 
            
            con.close();
        } 
        catch (SQLException ex) 
        {
            System.out.println("Statement Hatası");
        }
        jPanel1.revalidate();
        jPanel1.repaint();
        repaint();
    }
    
    public void vt_masaBosalt()
    {
        int reply = JOptionPane.showConfirmDialog(null,"Masa "+ secilen_masa+" Hesabını Silmek İçin 'Yes' e Basınız", " ", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) 
        {
            Connection con;
            con = null;
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Bağlantı nesnesi
                String strdatabase = "jdbc:ucanaccess://otomasyonVT.accdb"; //veritabanının ismi
                con = DriverManager.getConnection(strdatabase); //Access-java bağlantısnı sağlayan jdbc sürücüsü ile bağlantı oluşturuluyor
                Statement stmt = con.createStatement();
                String strSQL;
                try {
                    stmt = con.createStatement();
                    strSQL ="delete from masa"+secilen_masa;
                    stmt.executeUpdate(strSQL);
                    }
                catch(Exception e)
                {
                    System.out.println(e);
                }  
            con.close();
            } 
            catch (Exception e) {
                System.out.println("Bağlantı Hatası");
            } 
        } 
        else {
            
        } 
        jPanel1.revalidate();
        jPanel1.repaint();
        repaint();
    }
    
    public void vt_masadanUrunSil()
    {
        if(secilen_masa!=0)
        {
            Connection con;
            con = null;
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Bağlantı nesnesi
                String strdatabase = "jdbc:ucanaccess://otomasyonVT.accdb"; //veritabanının ismi
                con = DriverManager.getConnection(strdatabase); //Access-java bağlantısnı sağlayan jdbc sürücüsü ile bağlantı oluşturuluyor
            } 
            catch (Exception e) {
                System.out.println("Bağlantı Hatası 1");
            }
            try {
                Statement stmt;
                String strSQL;
                stmt = con.createStatement();
                ResultSet rs;
                try {
                    //stmt = con.createStatement();
                    rs = stmt.executeQuery("SELECT * FROM masa"+secilen_masa +" where Urun='"+urun_aktar+"'");
                    rs.next();
                    int adet_temp = rs.getInt("Adet") ;
                    if(adet_temp>1)
                    {
                        adet_temp=adet_temp-1;
                        strSQL ="update masa"+secilen_masa+" set adet="+adet_temp+" where Urun='"+urun_aktar+"'";
                        stmt.executeUpdate(strSQL);
                        con.close();
                    }
                    else
                    {
                        strSQL ="delete from masa"+secilen_masa+" where Urun='"+urun_aktar+"'";
                        stmt.executeUpdate(strSQL);
                    }
                    
                }
                catch(Exception e)
                {
                    System.out.println("4");
                }
            }
            catch(Exception e)
            {
                System.out.println("2");
            }  
            
        }
        vt_hesapTabloyaYaz();
    }
    
    public void vt_urunEkle()
    {
        if(secilen_kategori==null)
        {
            
        }
        else
        {
            Connection con;
            con = null;
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Bağlantı nesnesi
                String strdatabase = "jdbc:ucanaccess://otomasyonVT.accdb"; //veritabanının ismi
                con = DriverManager.getConnection(strdatabase); //Access-java bağlantısnı sağlayan jdbc sürücüsü ile bağlantı oluşturuluyor
                Statement stmt = con.createStatement();
                String strSQL;
                try {
                    stmt = con.createStatement();
                    strSQL ="insert into "+secilen_kategori+"(Urun,Fiyat) Values('"+eklenecek_urun+"',"+urun_fiyat+")";
                    stmt.executeUpdate(strSQL);
                    }
                catch(Exception e)
                {
                    System.out.println(e);
                }  
                con.close();
            } 
            catch (Exception e) {
                System.out.println("Bağlantı Hatası");
            } 
        }
        vt_urunTabloyaYaz();
    }
    
    public void vt_urunTabloyaYaz()
    {
        if(secilen_kategori==null)
        {
            button_urunEkle.setVisible(false);
        }
        else
        {
            button_urunEkle.setVisible(true);
            Connection con;
            con = null;
            try
            {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Bağlantı nesnesi
                String strdatabase = "jdbc:ucanaccess://otomasyonVT.accdb"; //veritabanının ismi
                con = DriverManager.getConnection(strdatabase); //Access-java bağlantısnı sağlayan jdbc sürücüsü ile bağlantı oluşturuluyor
            }
            catch(Exception e)
            {        
                System.out.println("bağlantı hatası");     
            }
            String strSQL ="select * from "+secilen_kategori;
            try {
                Statement stmt = con.createStatement();
                Object[][] obj;
            
                ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM "+secilen_kategori);
                rs.next();
                int iCount = rs.getInt("rowcount") ;
                rs.close() ;
            
                rs = stmt.executeQuery(strSQL);

                obj= new Object [iCount][2];

                iCount = 0;
            
                while ( rs.next() ) 
                {
                    obj[iCount][0] = rs.getString("Urun");
                    obj[iCount][1] = rs.getDouble("Fiyat");
                    iCount = iCount+1;
                }
                DefaultTableModel model=new javax.swing.table.DefaultTableModel(obj,new String [] {"Ürün","Birim Fiyat"})
                {
                    @Override
                    
                    public boolean isCellEditable(int row, int column) 
                    {
                        return false;
                    }
                };
            
                jTable2.setModel(model);
                

                
                rs.close() ;    
                con.close();
            } 
            catch (SQLException ex) 
            {
                System.out.println("Statement Hatası");
            }
        }
        label_kategoriIsim.setText(kategoriIsim);
        jPanel1.revalidate();
        jPanel1.repaint();
        repaint();
    }
    
    public void vt_urunAktar()
    {
        if(secilen_masa!=0)
        {
            Connection con;
            con = null;
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Bağlantı nesnesi
                String strdatabase = "jdbc:ucanaccess://otomasyonVT.accdb"; //veritabanının ismi
                con = DriverManager.getConnection(strdatabase); //Access-java bağlantısnı sağlayan jdbc sürücüsü ile bağlantı oluşturuluyor
            } 
            catch (Exception e) {
                System.out.println("Bağlantı Hatası 1");
            }
            try {
                Statement stmt;
                String strSQL;
                stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM masa"+secilen_masa +" where Urun='"+urun_aktar+"'");
                rs.next();
                int iCount = rs.getInt("rowcount") ;
                rs.close();
                if(iCount<1)
                {
                    try {
                        //stmt = con.createStatement();
                        strSQL ="insert into masa"+secilen_masa+"(Urun,Adet,Fiyat) Values('"+urun_aktar+"',1,"+fiyat_aktar+")";
                        stmt.executeUpdate(strSQL);
                        con.close();
                    }
                    catch(Exception e)
                    {
                        System.out.println("3");
                    }
                }
                else 
                {
                    try {
                        //stmt = con.createStatement();
                        rs = stmt.executeQuery("SELECT * FROM masa"+secilen_masa +" where Urun='"+urun_aktar+"'");
                        rs.next();
                        int adet_temp = rs.getInt("Adet") ;
                        adet_temp=adet_temp+1;
                        strSQL ="update masa"+secilen_masa+" set adet="+adet_temp+" where Urun='"+urun_aktar+"'";

                        stmt.executeUpdate(strSQL);
                        con.close();
                    }
                    catch(Exception e)
                    {
                        System.out.println("4");
                    }
                }       
            }
            catch(Exception e)
            {
                System.out.println("2");
            }  
            vt_hesapTabloyaYaz();
        }
    }
    
    public void masa_renk(int kontrol)
    {
        if(kontrol==1)
        {
            butonlar.get(secilen_masa-1).setBackground(new java.awt.Color(255, 153, 0)); 
        }
        else
        {
            butonlar.get(secilen_masa-1).setBackground(new java.awt.Color(153, 255, 153));
        }
    }
    
    public void ilk_renkAtama()
    {
        for(int i=0;i<masaSayisi;i++)
        {
            secilen_masa=i+1;
            vt_hesapTabloyaYaz();
        }
        secilen_masa=1;
        vt_hesapTabloyaYaz();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(otomasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(otomasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(otomasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(otomasyon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new otomasyon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton_anaYemekler;
    private javax.swing.JButton buton_aperatifler;
    private javax.swing.JButton buton_hesapSil;
    private javax.swing.JButton buton_icecekler;
    private javax.swing.JButton buton_kahveler;
    private javax.swing.JButton buton_tost;
    private javax.swing.JButton button_frame1_approve;
    private javax.swing.JButton button_tatlilar;
    private javax.swing.JButton button_urunEkle;
    private javax.swing.JButton button_urunEkleFrame2;
    private javax.swing.JButton button_urunSil;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_kategoriIsim;
    private javax.swing.JLabel label_secilenKategori;
    private javax.swing.JLabel label_toplamHesap;
    private javax.swing.JTextField textfield_eklenecekUrunAd;
    private javax.swing.JTextField textfield_eklenecekUrunFiyat;
    // End of variables declaration//GEN-END:variables
}
